/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.65
 * Generated at: 2022-01-03 09:42:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t<meta charset=\"utf-8\">\n");
      out.write("\t<link rel=\"icon\" type=\"image/ico\" href=\"resources/img/favicon/EMS_favicon.ico\">\n");
      out.write("\t<title>Vizuo Portable - Login</title>\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no\">\n");
      out.write("\t<!-- STYLESHEETS --><!--[if lt IE 9]><script src=\"js/flot/excanvas.min.js\"></script><script src=\"http://html5shiv.googlecode.com/svn/trunk/html5.js\"></script><script src=\"http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js\"></script><![endif]-->\n");
      out.write("\t<!-- thanhuy.nguyen ADD START -->\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\t\thref=\"resources/ext/css/cloud-admin-daviteq.css\">\n");
      out.write("\t<!-- thanhuy.nguyen ADD END -->\n");
      out.write("\t\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" \n");
      out.write("\t\thref=\"resources/ext/css/font-awesome/css/font-awesome.min.css\"> \n");
      out.write("\t\n");
      out.write("\t<!-- ANIMATE -->\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/ext/css/animatecss/animate.min.css\" />\n");
      out.write("\t\n");
      out.write("\t<style type=\"text/css\">\n");
      out.write("\t.login {\n");
      out.write("\t\tbackground: url(resources/img/daviteq-icon/back-ground-login.png) no-repeat center center fixed; \n");
      out.write("\t\t-webkit-background-size: 100% 100%;\n");
      out.write("\t\t-moz-background-size: 100% 100%;\n");
      out.write("\t\t-o-background-size: 100% 100%;\n");
      out.write("\t\tbackground-size: 100% 100%;\n");
      out.write("\t}\n");
      out.write("\t#i_username {\n");
      out.write("\t\tmin-width: 250px;\n");
      out.write("\t}\n");
      out.write("\t#i_password {\n");
      out.write("\t\tmin-width: 250px;\n");
      out.write("\t}\n");
      out.write("\t#btnSubmit {\n");
      out.write("\t\tmin-width: 250px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t</style>\n");
      out.write("\t<!-- FONTS -->\n");
      out.write("\t<!-- <link rel='stylesheet' type='text/css' \n");
      out.write("\t\thref='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700'> -->\n");
      out.write("\t\t\n");
      out.write("\t<script type=\"text/javascript\" src=\"resources/js/backbone/utils/ajax_wrapper.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body class=\"login\">\n");
      out.write("\t<!-- PAGE -->\n");
      out.write("\t<section id=\"page\" style=\"display: none\">\n");
      out.write("\t\t<!-- HEADER -->\n");
      out.write("\t\t<header>\n");
      out.write("\t\t\t<!-- NAV-BAR -->\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!--/NAV-BAR -->\n");
      out.write("\t\t</header>\n");
      out.write("\t\t<!--/HEADER -->\n");
      out.write("\t\t\n");
      out.write("\t\t<div id=\"ajax-content\">\n");
      out.write("\t\t\t<section id=\"login_bg\">\n");
      out.write("\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-3\" style=\"margin-left: 10%; margin-top: 3%\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"login-box-plain\">\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <h2 class=\"bigintro\">Sign in</h2>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"divide-40\"></div> -->\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <form action='j_spring_security_check' name=\"login-form\" method=\"POST\" role=\"form\"> -->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-3 col-md-offset-0\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"logo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"resources/img/logo.bak.png\" height=\"70\" alt=\"logo name\" style=\"width:280px;margin-left:-15px\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"clear: both; height: 30px;\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t<form action='doLogin' name=\"login-form\" method=\"POST\" id=\"frmLogin\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\" id=\"fg-un\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"exampleInputEmail1\" style=\"color: #ffffff;\">Username or email</label> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-envelope\"></i> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Please enter username or email\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"\" name=\"username\" id=\"username\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"error-span\" id=\"un-error-span\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\" id=\"fg-pw\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"exampleInputPassword1\" style=\"color: #ffffff;\">Password</label> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-lock\"></i> \n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" placeholder=\"Please enter password\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"\" name=\"password\" id=\"password\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"error-span\" id=\"pw-error-span\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"checkbox\" style=\"color: #ffffff;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"chkIsRemember\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width: auto; margin-top:3px\" name=\"isRemember\"> Remember me\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\" style=\"display: none;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"browser_info\" id=\"txtBrowserInfo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"captcha-div\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"exampleInputPassword1\">Captcha</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-picture-o\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" name='captcha' type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Type character below\" value=\"\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group \">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img id=\"image-captcha\" src=\"\" /> <span\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"vertical-align: middle\" class=\"fa fa-refresh fa-2x\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"refreshCaptcha()\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"error\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button id=\"btnSubmit\"  type=\"button\" class=\"btn btn-danger\" onclick=\"return doLogin()\">Sign in</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"login-helpers\" style=\"margin-top:-10px\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"forgot-password\" style=\"color:#ffffff;\">Forgot your password?</a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"login-helpers\" style=\"margin-top:10px\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"https://play.google.com/store/apps/details?id=com.daviteq.vizou\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"color:#ffffff; display:none\" target=\"_blank\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img width=\"115px\" height=\"35px\" src=\"resources/img/google_play.png\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"https://play.google.com/store/apps/details?id=com.daviteq.vizou\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"color:#ffffff; display:none\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img width=\"115px\" height=\"35px\" src=\"resources/img/apple_app.png\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</section>\n");
      out.write("\t\t\t<!--/LOGIN -->\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t<!--/PAGE -->\n");
      out.write("\t<!-- JAVASCRIPTS -->\n");
      out.write("\t<!-- Placed at the end of the document so the pages load faster -->\n");
      out.write("\t<!-- JQUERY -->\n");
      out.write("\t<script type=\"text/javascript\" \n");
      out.write("\t\tsrc=\"resources/js/jquery/jquery-2.1.0.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script type=\"text/javascript\" \n");
      out.write("\t\tsrc=\"resources/js/jquery/jquery.cookie.js\"></script>\n");
      out.write("\t\t\n");
      out.write("\t<script type=\"text/javascript\" \n");
      out.write("\t\tsrc=\"resources/js/authentication/authentication.js\"></script>\n");
      out.write("\t<!-- CUSTOM SCRIPT -->\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\tfunction swapScreen(id) {\n");
      out.write("\t\t\tjQuery('.visible').removeClass('visible animated fadeInUp');\n");
      out.write("\t\t\tjQuery('#'+id).addClass('visible animated fadeInUp');\n");
      out.write("\t\t}\n");
      out.write("\t\tjQuery(document).ready(function() {\t\t\n");
      out.write("\t\t\tswapScreen('login_bg');\n");
      out.write("\t\t\t$(\"#i_username\").focus();\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("\t<!-- /JAVASCRIPTS -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
